name: Widgets - Release

on:
  workflow_run:
    workflows: ["Widgets - CI"]
    branches: [ main ]
    types:
      - completed
    paths:
      - 'src/Widgets/**'
      - 'src/Widgets.Abstractions/**'
jobs:
  publish-nuget:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Install dependencies
      run: dotnet restore
      working-directory: ./src
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: ./src
    - name: Publish to NuGet
      run: dotnet nuget push /src/Widgets/bin/Release/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source "https://api.nuget.org/v3/index.json" --skip-duplicate